import type { Metadata } from "next";
import "./globals.css";
import GlobalProviders from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="scroll-smooth">
          <body className="antialiased bg-forge-charcoal text-white overflow-x-hidden">
            <GlobalProviders>
                {children}
            </GlobalProviders>
          </body>
      </html>
  );
}
