version: '3.9'

services:
  smithy_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smithy_backend
    environment:
      - SMITHY_ENV=production
      - DATABASE_URL=postgresql+asyncpg://smithy:smithy@postgres:5432/smithy
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - smithy_network

  postgres:
    image: postgres:15-alpine
    container_name: smithy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smithy
      POSTGRES_USER: smithy
      POSTGRES_PASSWORD: smithy
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smithy -d smithy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smithy_network

  redis:
    image: redis:7-alpine
    container_name: smithy_redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smithy_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  smithy_network:
    driver: bridge
