"""add user lock fields

Revision ID: 3b7b1c985503
Revises: d257b753aa69
Create Date: 2025-07-06 17:59:37.747302+00:00

🚧 SMITHY MIGRATION 🚧
This file was automatically forged by Alembic.
Edit only if you know what you're doing.
"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7b1c985503'
down_revision: Union[str, Sequence[str], None] = 'd257b753aa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, comment='User login is locked.'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='User login allowed in time.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###
