"""update relationship

Revision ID: d257b753aa69
Revises: d80f835b08ad
Create Date: 2025-07-02 14:17:11.553564+00:00

🚧 SMITHY MIGRATION 🚧
This file was automatically forged by Alembic.
Edit only if you know what you're doing.
"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d257b753aa69"
down_revision: Union[str, Sequence[str], None] = "d80f835b08ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "external_id")
    op.drop_column("tasks", "external_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "external_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="External system URL",
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "external_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="External system ID (GitHub, Jira, etc.)",
        ),
    )
    # ### end Alembic commands ###
